import io
import threading
import time
import requests
import streamlit as st
from PIL import Image

API_URL = "https://ai-image-detector-api-br5c.onrender.com"

st.set_page_config(page_title="AI Image Detector")
st.title("AI Image Detector")
st.write("Upload an Image to check if it's real or generated by AI")

# --- 1. Background Warm-Up Thread ---
if "woken_backend" not in st.session_state:
    st.session_state.woken_backend = True

    def ping_backend():
        try:
            # Short timeout ping to trigger Render container boot early
            requests.get(f"{API_URL}/", timeout=5)
        except Exception:
            pass  # Fire and forget; doesn't matter if it times out

    threading.Thread(target=ping_backend, daemon=True).start()


def preprocess_and_compress(image_file, target_size=(128, 128)):
    """Pre-resizes the image to 128x128 and converts to compressed JPEG bytes."""
    img = Image.open(image_file).convert("RGB")
    img = img.resize(target_size, Image.Resampling.LANCZOS)

    buffer = io.BytesIO()
    img.save(buffer, format="JPEG", quality=85)
    return buffer.getvalue()


# --- 2. Predict Function with Auto-Retry ---
def predict_with_retry(optimized_bytes, max_retries=3):
    """Retries request automatically if Render is still booting up."""
    for attempt in range(1, max_retries + 1):
        try:
            # Dynamic timeout increases on each attempt
            timeout = 30 * attempt
            response = requests.post(
                f"{API_URL}/predict",
                files={"image": ("input.jpg", optimized_bytes, "image/jpeg")},
                timeout=timeout,
            )
            return response
        except (requests.exceptions.Timeout, requests.exceptions.ConnectionError):
            if attempt < max_retries:
                st.warning(
                    f"Render server is waking up (Attempt {attempt}/{max_retries}). Retrying in 5 seconds..."
                )
                time.sleep(5)
            else:
                raise


uploaded_file = st.file_uploader("Choose an Image...", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_container_width=True)
    st.write("Press Analyze Image below to show results")

    if st.button("Analyze Image"):
        with st.spinner("Analyzing pixels (waking up Render backend if idle)..."):
            try:
                optimized_bytes = preprocess_and_compress(uploaded_file)
                response = predict_with_retry(optimized_bytes, max_retries=3)

                if response.status_code == 200:
                    result = response.json()

                    label = result.get("label", "Unknown")
                    confidence = result.get("confidence", 0)
                    scores = result.get("scores", {})
                    ai_prob = scores.get("ai_generated", 0.0)

                    st.subheader(f"Prediction: **{label}**")
                    st.write(f"Confidence: **{confidence}%**")
                    st.progress(float(ai_prob))
                    st.caption(f"AI Likelihood Score: {round(ai_prob * 100, 1)}%")
                else:
                    st.error(f"Server Error ({response.status_code}): {response.text}")

            except (requests.exceptions.Timeout, requests.exceptions.ConnectionError):
                st.error(
                    "The backend server took too long to wake up. Please click 'Analyze Image' once more to complete the request."
                )
            except Exception as e:
                st.error(f"Error making prediction: {e}")