import io
import requests
import streamlit as st
from PIL import Image

st.set_page_config(page_title="AI Image Detector")
st.title("AI Image Detector")
st.write("Upload an Image to check if it's real or generated by AI")

uploaded_file = st.file_uploader("Choose an Image...", type=["jpg", "png", "jpeg"])


def preprocess_and_compress(image_file, target_size=(128, 128)):
    """Pre-resizes the image to 128x128 and converts to compressed JPEG bytes."""
    img = Image.open(image_file).convert("RGB")

    # Match model input dimensions directly on client side
    img = img.resize(target_size, Image.Resampling.LANCZOS)

    # Save optimized bytes to memory
    buffer = io.BytesIO()
    img.save(buffer, format="JPEG", quality=85)
    return buffer.getvalue()


if uploaded_file is not None:
    # Display full preview to user
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", width="stretch")

    if st.button("Analyze Image"):
        with st.spinner("Optimizing & Analyzing Pixels (initial load may take ~45s if Render is waking up)..."):
            try:
                # Resize to 128x128 JPEG bytes before sending over network
                optimized_bytes = preprocess_and_compress(uploaded_file)

                response = requests.post(
                    "https://ai-image-detector-api-br5c.onrender.com/predict",
                    files={"image": ("input.jpg", optimized_bytes, "image/jpeg")},
                    timeout=60
                )

                if response.status_code == 200:
                    result = response.json()

                    # Extract response data matching app.py payload structure
                    label = result.get("label", "Unknown")
                    confidence = result.get("confidence", 0)
                    scores = result.get("scores", {})
                    ai_prob = scores.get("ai_generated", 0.0)

                    st.subheader(f"Prediction: **{label}**")
                    st.write(f"Confidence: **{confidence}%**")

                    # Display progress bar (expects float between 0.0 and 1.0)
                    st.progress(float(ai_prob))
                    st.caption(f"AI Likelihood Score: {round(ai_prob * 100, 1)}%")
                else:
                    st.error(f"Server Error ({response.status_code}): {response.text}")

            except requests.exceptions.Timeout:
                st.error("Connection timed out while waiting for Render to wake up. Click 'Analyze Image' again.")
            except Exception as e:
                st.error(f"Error making prediction: {e}")