import streamlit as st
import requests
from PIL import Image
st.set_page_config(page_title="AI Image Detector")
st.title("AI Image Detector")
st.write("Upload an Image to check if it's real or generated by AI")

uploaded_file = st.file_uploader("Choose an Image...", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", width="stretch")

    if st.button("Analyze Image"):
        with st.spinner("Analyzing Pixels..."):
            img_bytes = uploaded_file.getvalue()
            response = requests.post(
                "https://ai-image-detector-api-br5c.onrender.com/predict",
                files={"image": (uploaded_file.name, img_bytes, uploaded_file.type)},
            )

            if response.status_code == 200:
                result = response.json()
                st.subheader(f"Prediction: **{result['label']}**")
                st.write(f"Confidence: **{result['confidence']}%**")
                ai_prob = result['scores'].get('ai_generated', 0.0)
                st.progress(ai_prob)
                st.caption(f"AI Likelihood: {round(ai_prob * 100, 1)}%")
            else:
                st.error("Error making prediction. Ensure FastAPI backend is running.")